import "./globals.css";
import { GlobalContextProvider } from "./context/context";
import ColorThemeProvider from "./context/colorThemeProvider";
import Navbar from "./components/navigation/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // dark:bg-secondary dark:text-primary
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-primary text-secondary dark:bg-secondary dark:text-primary">
        <GlobalContextProvider>
          <ColorThemeProvider>
            <Navbar />
            <div className="overflow-y-scroll h-screen">{children}</div>
          </ColorThemeProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
