import "./globals.css";
import { GlobalContextProvider } from "./context/context";
import ColorThemeProvider from "./context/colorThemeProvider";
import Navbar from "./components/navigation/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-secondary dark:bg-secondary dark:text-primary overflow-hidden">
        <GlobalContextProvider>
          <ColorThemeProvider>
            <Navbar />
            <div
              className={`relative flex-grow overflow-y-auto overflow-x-hidden h-screen min-h-screen`}
            >
              {children}
            </div>
          </ColorThemeProvider>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
